### ISSUE TITLE
App crash when using in frame

### ISSUE THREAD

**Issue by academici** [NativeScript/nativescript-imagepicker#210]
I use latest nativescript-vue with template
`<Page @loaded="appLoaded">
      <GridLayout columns="*" rows="*, auto">
        <StackLayout row="0">
          <Frame><router-view/></Frame>
        </StackLayout>
        <app-bottombar></app-bottombar>
      </GridLayout>
    </Page>`

After selecting an image I get an error:
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to resume activity {org.nativescript.application/com.tns.NativeScriptActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:4309)
	at android.view.ViewGroup.addView(ViewGroup.java:4145)
	at android.view.ViewGroup.addView(ViewGroup.java:4086)
	at android.view.ViewGroup.addView(ViewGroup.java:4059)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:985)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
	at android.app.BackStackRecord.run(BackStackRecord.java:793)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
	at android.app.FragmentController.execPendingActions(FragmentController.java:325)
	at android.app.Activity.performResume(Activity.java:6306)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)

### Which platform(s) does your issue occur on?
emulator Nexus_5X_API_23

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.2.3
- Cross-platform modules: 4.2.0
- Runtime(s): 4.2.0
- Plugin(s): Only nativescript-imagepicker(6.0.3)

**Comment by tbozhikov** [comment]
Hi @academici, do you have a sample project that reproduces the behavior? A git repo would be best to play with.
Thanks in advance!

**Comment by academici** [comment]
@tbozhikov In the base template with the frame plugin works, then it's in some third-party plugin.
Thanks
