### ISSUE TITLE
Failed to find module: "nativescript-imagepicker"

### ISSUE THREAD

**Issue by dantedubon** [NativeScript/nativescript-imagepicker#23]
Hello, I am using the nativescript image picker with angular2 and I am having the following error using the Android emulator (iOS works well): 
`java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Failed to find module: "nativescript-imagepicker", relative to: /app/tns_modules/
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556)
	at android.app.ActivityThread.access$1500(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: com.tns.NativeScriptException: Failed to find module: "nativescript-imagepicker", relative to: /app/tns_modules/
	at com.tns.Module.resolvePathHelper(Module.java:220)
	`

My component is importing the image picker using:
 `var imagepickerModule = require("nativescript-imagepicker");` 

Wich could be the error?

Thanks in advance

**Comment by PanayotCankov** [comment]
Failed npm download, or perhaps --save-dev instead of --save. This shouldn't normally happen.
