### ISSUE TITLE
Error running on android. Execution failed for task ':asbg:generateBindings'.

### ISSUE THREAD

**Issue by Yamilquery** [NativeScript/nativescript-imagepicker#83]
Hi,

When I run my project with:

tns run android --emulator

I get the following error.

```
:copyTypings SKIPPED
:asbg:generateInterfaceNamesList
:asbg:traverseJsFiles
:asbg:runAstParser
Running full build
finished with reading lines with js files
Warning: there already is an extend called com.tns.NativeScriptActivity.
Warning: there already is an extend called com.tns.FragmentClass.
:asbg:generateBindings
Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
/Users/yamildiazaguirre/Documents/node/LAaps/levenmas/platforms/android/src/main/java/com/tns/gen/android/content/BroadcastReceiver_frnal_ts_helpers_l58_c38__BroadcastReceiver.java
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:59)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)
:asbg:generateBindings FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/yamildiazaguirre/Documents/node/LAaps/levenmas/platforms/android/build-tools/android-static-binding-generator/build.gradle' line: 251

* What went wrong:
Execution failed for task ':asbg:generateBindings'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 32.965 secs
Multiple errors were thrown:
Command ./gradlew failed with exit code 1
# run android
```

When I remove the module imagepicker I get no error.

My package.json

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.levenmas",
    "tns-ios": {
      "version": "3.0.0-rc.1-2017-3-28-2"
    },
    "tns-android": {
      "version": "3.0.0-rc.1"
    }
  },
  "dependencies": {
    "@angular/animations": "4.0.0",
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/router": "4.0.0",
    "email-validator": "^1.0.7",
    "moment": "^2.18.1",
    "nativescript-angular": "rc",
    "nativescript-imagepicker": "^2.5.1",
    "nativescript-phone": "^1.3.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "rc",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.16.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.4.0",
    "typescript": "~2.2.1"
  }
}

```

**Comment by tsonevn** [comment]
Hi @Yamilquery,
The above-given error has been related to that fact that in your project is used @rc `android-runtime` and `modules` with  `nativescript-imagepicker` version from npm which is not compatible with @rc.
The plugin has been migrated to @rc in the repository, however it is not published in npm.
At this point, you could build `tgz` file locally on your side by following the below given instructions.
1. `git clone https://github.com/NativeScript/nativescript-imagepicker`
2. `cd nativescript-imagepicker`
3. `npm install`
4, `tsc`
5. `npm pack` - in the plugin's folder you will find the generated `tgz` file.
6, to use it in your project just run `tns plugin add <path to the tgz file>`

Hope this helps.
